---
namespace: threescale
sso_project: rh-sso
backend_project: international
apicurio_project: apicurio
gogs_project: gogs
microcks_project: microcks
sso_version: ose-v1.4.9
ocp_domain: 3901.openshiftworkshop.com
ocp_apps_domain: apps.3901.openshiftworkshop.com
usersno: 20
che: true
fuse: true
threescale: true
apicurio: true
gogs: true
microcks: true
sso: true
backend: true
user_projects: true
configure_only: false
create_tenants: true
create_realms: true
create_ides: true
create_fuses: true