---
build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

POSTGRESQL_MEMORY_LIMIT: 512Mi
PROMETHEUS_MEMORY_LIMIT: 255Mi
META_MEMORY_LIMIT: 1Gi
SERVER_MEMORY_LIMIT: 2Gi
MAX_INTEGRATIONS_PER_USER: 20


# userId / password for AMQ used in syndesisio
mq_username: amq
mq_password: topSecret

##########          supported fuse ignite       #################
SYNDESIS_REGISTRY: registry.access.redhat.com 
SYNDESIS_REGISTRY_WEB_SUBCONTEXT: fuse7
product_name: fuse-ignite

# Corresponds to GPTE fork of community syndesis master branch
#   This branch implements the following:
#       1)  DCs in a paused state
ignite_template_name: "{{ product_name }}"
syndesisio_url: https://raw.githubusercontent.com/gpe-mw-training/fuse-ignite-install/gpte-1.3

fuse_ignite_is_yaml: "{{syndesisio_url}}/resources/fuse-ignite-image-streams.yml"
syndesisio_sa_yml:  "{{syndesisio_url}}/resources/serviceaccount-as-oauthclient-restricted.yml"
syndesisio_template_yml: "{{syndesisio_url}}/resources/fuse-ignite-ocp.yml"
#################################################################
