---
- name: Make sure we go back to default project
  shell: "oc project default"

- name: Create Apicurio app
  shell: "oc new-app -f {{ apicurio_template_url }} \
  -p UI_ROUTE=apicurio-studio.{{ ocp_apps_domain }} -p API_ROUTE=apicurio-studio-api.{{ ocp_apps_domain }} \
  -p WS_ROUTE=apicurio-studio-ws.{{ ocp_apps_domain }} -p AUTH_ROUTE=sso-{{sso_project}}.{{ocp_apps_domain}} {{ apicurio_template_params }} -n {{ apicurio_project }}"
  register: apicurio_create
  failed_when: apicurio_create.stderr != '' and 'already exists' not in apicurio_create.stderr
  when: configure_only == 'false'

- name: Get SSO token
  shell: "curl --insecure -X POST 'https://sso-{{sso_project}}.{{ocp_apps_domain}}/auth/realms/master/protocol/openid-connect/token' \
  -H 'Content-Type: application/x-www-form-urlencoded' -d 'username={{ eval_rhsso_admin_username | default('keyadmin') }}' -d 'password={{ eval_rhsso_admin_password | default('keypassword') }}' -d 'grant_type=password' -d 'client_id=admin-cli'"
  register: token_text
  when: create_realms

- set_fact: TKN={{ (token_text.stdout | from_json).access_token }}
  when: create_realms

- debug: var=TKN
  when: create_realms

- name: Get Apicurio realm
  uri:
    url: 'https://raw.githubusercontent.com/jbossdemocentral/3scale-api-workshop/master/support/templates/apicurio-realm.json'
    return_content: yes
  register: apicurio_realm
  when: create_realms

- debug: var=apicurio_realm.content
  when: create_realms

- set_fact: realm={{ apicurio_realm.content | regex_replace('APICURIO_UI_URL', 'http://apicurio-studio.' + ocp_apps_domain) }}
  when: create_realms

- debug: var=realm
  when: create_realms

- name: Create Apicurio Realm
  uri: 
    url: 'https://sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms'
    method: POST
    body: "{{ realm }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ TKN }}"
    return_content: yes
    validate_certs: no
    status_code: [201, 409]
  when: create_realms
  
- name: Create Apicurio users
  uri: 
    url: 'https://sso-{{sso_project}}.{{ocp_apps_domain}}/auth/admin/realms/{{apicurio_project}}/users'
    method: POST
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer {{ TKN }}"
    body: "{\"username\":\"{{ item }}\",\"enabled\":true,\"firstName\":\"{{ item }}\",\"credentials\":[{\"type\":\"password\",\"value\":\"openshift\",\"temporary\":false}]}"
    body_format: json
    validate_certs: no
    status_code: [201, 409]
  with_sequence: start=1 end={{ usersno }} format=user%d
  when: create_realms
